on: pull_request

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Run pre-commit (prek) on the changed files
        uses: j178/prek-action@v2.0.6
        with:
          extra-args: --from-ref ${{ GITHUB_BASE_REF }} --to-ref HEAD
